FROM alpine

MAINTAINER Zonesan <chaizs@asiainfo.com>

ENV TIME_ZONE=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TIME_ZONE /etc/localtime && echo $TIME_ZONE > /etc/timezone

COPY bin/linux/svc-amount-agent /svc-amount-agent

EXPOSE 8080

ENTRYPOINT /svc-amount-agent

